version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: cta4CreateSqlServer
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ctaPass1!"
    healthcheck:
      test: ["CMD", "sqlcmd", "-U", "sa", "-P", "ctaPass1!", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  clinicaltrial:
    build:
      context: .  # Build the Docker image from the current directory
      dockerfile: Dockerfile  # Use the specified Dockerfile for the build
    container_name: clinical-trial-api
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ClinicalTrial;User=sa;Password=ctaPass1!"
    command: >
      sh -c "dotnet ef database update --project /app/ClinicalTrial.Infrastructure && dotnet ClinicalTrial.App.dll"